email: "agwhaley@whaleylawfirm.com"
full_name: "Aaron Whaley"
name: "Aaron"
background: >
  Aaron is the owner of and lawyer for the Whaley Law Firm. The Whaley Law Firm is a personal injury firm which handles primarily car accidents, slip and falls, and workers compensation.
timezone: "America/New_York"
schedule_preferences: >-
  By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: |
  Whaley Law Firm has several employees that will be either receiving mail from or forwarding mail to.  Bryce Koon is an associate attorney. Emails that involve litigation, or cases that have already been filed in a court will be forwraded to Bryce. His email address is bryce@whaleylawfirm.com. Bryce also handles all workers compensation cases. Sarena Tuttle is the firm paralegal. She assists Bryce on all litigation and workers compensation cases and so she should be cc'd on any emails that involve litigation or workers compensation. Her email address is sarena@whaleylawfirm.com. Justin Chumbley is the head case manager and he handles all cases(except workers comp) that are not in litigation. His email address is justin@whaleylawfirm.com and all emails asking about cases or clients should be forwarded to him. Faye Gaither is in charge of client relations and she handles all emails from clients. Her email address is faye@whaleylawfirm.com. Additionally, any voicemails regarding the relevant topics should be forwarded accordingly.  
response_preferences:
rewrite_preferences: |
  Aaron has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Aaron REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Aaron
  - When Aaron is casual, he generally does not include any greetings or sign offs, and just directly says his message

triage_no: |
  -= Automatic notifications of payments made
  - Any email that has the option to unsubscribe
  - Anything that looks like they are trying to sell me something
  - Automated emails from services that are spamming Aaron
  - Cold outreach from vendors - this happens a lot as people try to sell Aaron things. He is not interested in these
  - Spam email

triage_notify: |
  - notifications of court filings
  - Emails from Blazeo Voice
  - voicemails, texts or faxes from Ring Central
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Anything that is pretty technically detailed about Whaley Law Firm. Aaron sometimes gets asked questions about Whaley Law Firm, \
  while he may not always respond to those he likes getting notified about them
  - Emails where there is a clear action item from Aaron based on a previous conversation
  - Emails about new clients that have been signed or if they have questions.

triage_email: |
  -  Emails from clients 
  - Emails from other Whaley Law Firm team members Justin@whaleylawfirm.com, Faye@whaleylawfirm.com, Bryce@whaleylawfirm.com, Sarena@whaleylawfirm.com, Jessa@whaleylawfirm.com, Aries@whaleylawfirm.com, or Jessica@whaleylawfirm.com 
  - Emails where Aaron has gotten added to a thread and he hasn't yet said hello
  - Emails where it seems like Aaron has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Aaron should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Aaron should do so.
  - Emails from other attorneys 
  - Emails about specific clients that are represented by the Whaley Law Firm

  
memory: true


